const express = require('express');
const crypto = require('crypto');
const https = require('https');

const app = express();
const PORT = process.env.PORT || 3000;
const WHOP_WEBHOOK_SECRET = process.env.WHOP_WEBHOOK_SECRET;
const TOLERANCE_SECONDS = 5 * 60;

// Meta Conversions API — Purchase event forwarding.
// META_CAPI_ACCESS_TOKEN must be generated by a human in Meta Events Manager
// (Data Sources > pixel 1543230227264583 > Settings > Conversions API >
// Generate access token) and set as an env var on this Coolify app. Until it's
// set, CAPI sending is a safe no-op (logged, not fatal) so webhook delivery
// keeps working either way.
const META_PIXEL_ID = process.env.META_PIXEL_ID || '1543230227264583';
const META_CAPI_ACCESS_TOKEN = process.env.META_CAPI_ACCESS_TOKEN || '';
const META_CAPI_TEST_EVENT_CODE = process.env.META_CAPI_TEST_EVENT_CODE || ''; // optional, for Test Events tab

if (!WHOP_WEBHOOK_SECRET) {
  console.error('WHOP_WEBHOOK_SECRET env var is not set — every webhook will be rejected.');
}

if (!META_CAPI_ACCESS_TOKEN) {
  console.warn(
    'META_CAPI_ACCESS_TOKEN is not set — Purchase events will be logged but NOT sent to ' +
    'Meta Conversions API. Generate one in Meta Events Manager (pixel ' + META_PIXEL_ID +
    ' > Settings > Conversions API > Generate access token) and set it on this app.'
  );
}

function sha256Hex(value) {
  return crypto.createHash('sha256').update(String(value).trim().toLowerCase()).digest('hex');
}

// Best-effort extraction of purchase details across the Whop payload shapes
// seen in practice ("payment.succeeded", "membership.went_valid", etc). Whop's
// exact field names have shifted across API versions, so this checks several
// plausible locations rather than assuming one fixed schema.
function extractPurchaseFields(event) {
  const d = event.data || {};
  const amountRaw =
    d.final_amount ?? d.amount ?? d.subtotal ?? d.total ??
    (d.plan && d.plan.renewal_price) ?? d.renewal_price ?? null;

  // Whop amounts are sometimes in dollars already, sometimes in cents. Treat
  // anything >= 1000 as cents (BloomRecorder's real price is ~$19-29, so a
  // value in the thousands is unambiguously cents).
  let value = amountRaw !== null ? Number(amountRaw) : null;
  if (value !== null && Number.isFinite(value) && value >= 1000) value = value / 100;

  const currency = (d.currency || 'usd').toUpperCase();
  const email = d.email || d.user_email || (d.user && d.user.email) || null;
  const eventId = event.id || d.id || crypto.randomUUID();

  return { value, currency, email, eventId };
}

function sendPurchaseToMetaCAPI(event) {
  if (!META_CAPI_ACCESS_TOKEN) {
    console.log('[CAPI] Skipped (no META_CAPI_ACCESS_TOKEN set):', JSON.stringify(event.data || {}));
    return;
  }

  const { value, currency, email, eventId } = extractPurchaseFields(event);

  const userData = {};
  if (email) userData.em = [sha256Hex(email)];

  const payload = {
    data: [
      {
        event_name: 'Purchase',
        event_time: Math.floor(Date.now() / 1000),
        event_id: eventId, // dedupes against any client-side pixel Purchase for the same order
        action_source: 'website',
        event_source_url: 'https://bloomrecorder.com/',
        user_data: userData,
        custom_data: {
          value: value !== null && Number.isFinite(value) ? value : 19.0,
          currency: currency || 'USD',
        },
      },
    ],
  };
  if (META_CAPI_TEST_EVENT_CODE) payload.test_event_code = META_CAPI_TEST_EVENT_CODE;

  const body = JSON.stringify(payload);
  const req = https.request(
    {
      hostname: 'graph.facebook.com',
      path: `/v21.0/${META_PIXEL_ID}/events?access_token=${encodeURIComponent(META_CAPI_ACCESS_TOKEN)}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    },
    (res) => {
      let resBody = '';
      res.on('data', (c) => (resBody += c));
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          console.log('[CAPI] Purchase event sent:', resBody);
        } else {
          console.error('[CAPI] Purchase event failed:', res.statusCode, resBody);
        }
      });
    }
  );
  req.on('error', (err) => console.error('[CAPI] Request error:', err));
  req.write(body);
  req.end();
}

// Whop event types that represent a completed purchase. Covers both the
// one-time-payment flow and the membership/subscription flow.
const PURCHASE_EVENT_TYPES = new Set([
  'payment.succeeded',
  'payment_succeeded',
  'membership.went_valid',
  'membership_went_valid',
  'membership.went_valid.v2',
]);

// Raw body needed for signature verification — must be the exact bytes Whop signed.
app.use(express.raw({ type: '*/*', limit: '1mb' }));

// Whop's dashboard has shown secrets as both "whsec_<base64>" (Standard Webhooks
// convention, per docs.whop.com) and "ws_<hex>" (seen in practice) — decode whichever
// we were actually given rather than assuming one.
function decodeSecret(raw) {
  const stripped = raw.replace(/^(whsec_|ws_)/, '');
  if (/^[0-9a-f]+$/i.test(stripped) && stripped.length % 2 === 0) {
    return Buffer.from(stripped, 'hex');
  }
  return Buffer.from(stripped, 'base64');
}

function verify(id, timestamp, rawBody, signatureHeader) {
  if (!WHOP_WEBHOOK_SECRET || !id || !timestamp || !signatureHeader) return false;

  const age = Math.abs(Math.floor(Date.now() / 1000) - Number(timestamp));
  if (!Number.isFinite(age) || age > TOLERANCE_SECONDS) return false;

  const secretBytes = decodeSecret(WHOP_WEBHOOK_SECRET);
  const signedContent = `${id}.${timestamp}.${rawBody.toString('utf8')}`;
  const expected = crypto.createHmac('sha256', secretBytes).update(signedContent).digest('base64');

  return signatureHeader
    .split(' ')
    .some((part) => {
      const [, sig] = part.split(',');
      if (!sig) return false;
      const a = Buffer.from(sig);
      const b = Buffer.from(expected);
      return a.length === b.length && crypto.timingSafeEqual(a, b);
    });
}

app.get('/health', (_req, res) => res.json({ ok: true }));

function handleWhopWebhook(req, res) {
  const id = req.header('webhook-id');
  const timestamp = req.header('webhook-timestamp');
  const signature = req.header('webhook-signature');

  if (!verify(id, timestamp, req.body, signature)) {
    console.warn('Rejected webhook: bad or missing signature', { id });
    return res.status(401).json({ ok: false });
  }

  let event;
  try {
    event = JSON.parse(req.body.toString('utf8'));
  } catch {
    return res.status(400).json({ ok: false });
  }

  // Respond fast; log now, wire up real delivery (email/Files-app grant/etc.) next.
  const eventType = event.type || event.action;
  console.log('Verified Whop webhook:', JSON.stringify({
    id,
    type: eventType,
    data: event.data
  }));

  if (PURCHASE_EVENT_TYPES.has(eventType)) {
    sendPurchaseToMetaCAPI(event);
  }

  res.status(200).json({ ok: true });
}

// Accepted at both the root and /webhooks/whop so either URL works in Whop's dashboard.
app.post('/', handleWhopWebhook);
app.post('/webhooks/whop', handleWhopWebhook);

app.listen(PORT, () => console.log(`bloomrecorder-webhook listening on ${PORT}`));
